var arr = [1, 2, 3, 4];
// console.time();
// arr.push(5);
// console.timeEnd();
// console.time();
// arr.pop();
// console.timeEnd();
console.time();
arr.shift();
console.timeEnd();
console.time();
arr.unshift(0);
console.timeEnd();
// console.log(arr);
